#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CocaChild")]
	public partial class CocaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnonStudent(AnonStudent instance);
    partial void UpdateAnonStudent(AnonStudent instance);
    partial void DeleteAnonStudent(AnonStudent instance);
    partial void InsertSurvey(Survey instance);
    partial void UpdateSurvey(Survey instance);
    partial void DeleteSurvey(Survey instance);
    partial void InsertClassLevel(ClassLevel instance);
    partial void UpdateClassLevel(ClassLevel instance);
    partial void DeleteClassLevel(ClassLevel instance);
    partial void InsertSchool(School instance);
    partial void UpdateSchool(School instance);
    partial void DeleteSchool(School instance);
    partial void InsertSeason(Season instance);
    partial void UpdateSeason(Season instance);
    partial void DeleteSeason(Season instance);
    partial void InsertState(State instance);
    partial void UpdateState(State instance);
    partial void DeleteState(State instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertStudentSurveyDate(StudentSurveyDate instance);
    partial void UpdateStudentSurveyDate(StudentSurveyDate instance);
    partial void DeleteStudentSurveyDate(StudentSurveyDate instance);
    partial void InsertStudentSurveyRating(StudentSurveyRating instance);
    partial void UpdateStudentSurveyRating(StudentSurveyRating instance);
    partial void DeleteStudentSurveyRating(StudentSurveyRating instance);
    partial void InsertSurveyClass(SurveyClass instance);
    partial void UpdateSurveyClass(SurveyClass instance);
    partial void DeleteSurveyClass(SurveyClass instance);
    partial void InsertSurveyDate(SurveyDate instance);
    partial void UpdateSurveyDate(SurveyDate instance);
    partial void DeleteSurveyDate(SurveyDate instance);
    #endregion
		
		public CocaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CocaChildConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CocaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CocaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CocaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CocaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AnonStudent> AnonStudents
		{
			get
			{
				return this.GetTable<AnonStudent>();
			}
		}
		
		public System.Data.Linq.Table<Survey> Surveys
		{
			get
			{
				return this.GetTable<Survey>();
			}
		}
		
		public System.Data.Linq.Table<ClassLevel> ClassLevels
		{
			get
			{
				return this.GetTable<ClassLevel>();
			}
		}
		
		public System.Data.Linq.Table<School> Schools
		{
			get
			{
				return this.GetTable<School>();
			}
		}
		
		public System.Data.Linq.Table<Season> Seasons
		{
			get
			{
				return this.GetTable<Season>();
			}
		}
		
		public System.Data.Linq.Table<State> States
		{
			get
			{
				return this.GetTable<State>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<StudentSurveyDate> StudentSurveyDates
		{
			get
			{
				return this.GetTable<StudentSurveyDate>();
			}
		}
		
		public System.Data.Linq.Table<StudentSurveyRating> StudentSurveyRatings
		{
			get
			{
				return this.GetTable<StudentSurveyRating>();
			}
		}
		
		public System.Data.Linq.Table<SurveyClass> SurveyClasses
		{
			get
			{
				return this.GetTable<SurveyClass>();
			}
		}
		
		public System.Data.Linq.Table<SurveyDate> SurveyDates
		{
			get
			{
				return this.GetTable<SurveyDate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnonStudents")]
	public partial class AnonStudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _UserId;
		
		private string _Password;
		
		private long _SurveyClassId;
		
		private System.Nullable<System.DateTime> _LoggedInDate;
		
		private System.Nullable<System.DateTime> _SavedDate;
		
		private EntitySet<StudentSurveyRating> _StudentSurveyRatings;
		
		private EntityRef<SurveyClass> _SurveyClass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSurveyClassIdChanging(long value);
    partial void OnSurveyClassIdChanged();
    partial void OnLoggedInDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLoggedInDateChanged();
    partial void OnSavedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSavedDateChanged();
    #endregion
		
		public AnonStudent()
		{
			this._StudentSurveyRatings = new EntitySet<StudentSurveyRating>(new Action<StudentSurveyRating>(this.attach_StudentSurveyRatings), new Action<StudentSurveyRating>(this.detach_StudentSurveyRatings));
			this._SurveyClass = default(EntityRef<SurveyClass>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AnonStudentId", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyClassId", DbType="BigInt NOT NULL")]
		public long SurveyClassId
		{
			get
			{
				return this._SurveyClassId;
			}
			set
			{
				if ((this._SurveyClassId != value))
				{
					if (this._SurveyClass.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSurveyClassIdChanging(value);
					this.SendPropertyChanging();
					this._SurveyClassId = value;
					this.SendPropertyChanged("SurveyClassId");
					this.OnSurveyClassIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoggedInDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LoggedInDate
		{
			get
			{
				return this._LoggedInDate;
			}
			set
			{
				if ((this._LoggedInDate != value))
				{
					this.OnLoggedInDateChanging(value);
					this.SendPropertyChanging();
					this._LoggedInDate = value;
					this.SendPropertyChanged("LoggedInDate");
					this.OnLoggedInDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SavedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SavedDate
		{
			get
			{
				return this._SavedDate;
			}
			set
			{
				if ((this._SavedDate != value))
				{
					this.OnSavedDateChanging(value);
					this.SendPropertyChanging();
					this._SavedDate = value;
					this.SendPropertyChanged("SavedDate");
					this.OnSavedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnonStudent_StudentSurveyRating", Storage="_StudentSurveyRatings", ThisKey="Id", OtherKey="AnonStudentId")]
		public EntitySet<StudentSurveyRating> StudentSurveyRatings
		{
			get
			{
				return this._StudentSurveyRatings;
			}
			set
			{
				this._StudentSurveyRatings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SurveyClass_AnonStudent", Storage="_SurveyClass", ThisKey="SurveyClassId", OtherKey="Id", IsForeignKey=true)]
		public SurveyClass SurveyClass
		{
			get
			{
				return this._SurveyClass.Entity;
			}
			set
			{
				SurveyClass previousValue = this._SurveyClass.Entity;
				if (((previousValue != value) 
							|| (this._SurveyClass.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SurveyClass.Entity = null;
						previousValue.AnonStudents.Remove(this);
					}
					this._SurveyClass.Entity = value;
					if ((value != null))
					{
						value.AnonStudents.Add(this);
						this._SurveyClassId = value.Id;
					}
					else
					{
						this._SurveyClassId = default(long);
					}
					this.SendPropertyChanged("SurveyClass");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StudentSurveyRatings(StudentSurveyRating entity)
		{
			this.SendPropertyChanging();
			entity.AnonStudent = this;
		}
		
		private void detach_StudentSurveyRatings(StudentSurveyRating entity)
		{
			this.SendPropertyChanging();
			entity.AnonStudent = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Surveys")]
	public partial class Survey : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _SchoolId;
		
		private int _ClassLevelId;
		
		private EntitySet<Student> _Students;
		
		private EntitySet<SurveyDate> _SurveyDates;
		
		private EntityRef<ClassLevel> _ClassLevel;
		
		private EntityRef<School> _School;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnSchoolIdChanging(long value);
    partial void OnSchoolIdChanged();
    partial void OnClassLevelIdChanging(int value);
    partial void OnClassLevelIdChanged();
    #endregion
		
		public Survey()
		{
			this._Students = new EntitySet<Student>(new Action<Student>(this.attach_Students), new Action<Student>(this.detach_Students));
			this._SurveyDates = new EntitySet<SurveyDate>(new Action<SurveyDate>(this.attach_SurveyDates), new Action<SurveyDate>(this.detach_SurveyDates));
			this._ClassLevel = default(EntityRef<ClassLevel>);
			this._School = default(EntityRef<School>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SurveyId", Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolId", DbType="BigInt NOT NULL")]
		public long SchoolId
		{
			get
			{
				return this._SchoolId;
			}
			set
			{
				if ((this._SchoolId != value))
				{
					if (this._School.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSchoolIdChanging(value);
					this.SendPropertyChanging();
					this._SchoolId = value;
					this.SendPropertyChanged("SchoolId");
					this.OnSchoolIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassLevelId", DbType="Int NOT NULL")]
		public int ClassLevelId
		{
			get
			{
				return this._ClassLevelId;
			}
			set
			{
				if ((this._ClassLevelId != value))
				{
					if (this._ClassLevel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassLevelIdChanging(value);
					this.SendPropertyChanging();
					this._ClassLevelId = value;
					this.SendPropertyChanged("ClassLevelId");
					this.OnClassLevelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Survey_Student", Storage="_Students", ThisKey="Id", OtherKey="SurveyId")]
		public EntitySet<Student> Students
		{
			get
			{
				return this._Students;
			}
			set
			{
				this._Students.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Survey_SurveyDate", Storage="_SurveyDates", ThisKey="Id", OtherKey="SurveyId")]
		public EntitySet<SurveyDate> SurveyDates
		{
			get
			{
				return this._SurveyDates;
			}
			set
			{
				this._SurveyDates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClassLevel_Survey", Storage="_ClassLevel", ThisKey="ClassLevelId", OtherKey="Id", IsForeignKey=true)]
		public ClassLevel ClassLevel
		{
			get
			{
				return this._ClassLevel.Entity;
			}
			set
			{
				ClassLevel previousValue = this._ClassLevel.Entity;
				if (((previousValue != value) 
							|| (this._ClassLevel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClassLevel.Entity = null;
						previousValue.Surveys.Remove(this);
					}
					this._ClassLevel.Entity = value;
					if ((value != null))
					{
						value.Surveys.Add(this);
						this._ClassLevelId = value.Id;
					}
					else
					{
						this._ClassLevelId = default(int);
					}
					this.SendPropertyChanged("ClassLevel");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="School_Survey", Storage="_School", ThisKey="SchoolId", OtherKey="Id", IsForeignKey=true)]
		public School School
		{
			get
			{
				return this._School.Entity;
			}
			set
			{
				School previousValue = this._School.Entity;
				if (((previousValue != value) 
							|| (this._School.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._School.Entity = null;
						previousValue.Surveys.Remove(this);
					}
					this._School.Entity = value;
					if ((value != null))
					{
						value.Surveys.Add(this);
						this._SchoolId = value.Id;
					}
					else
					{
						this._SchoolId = default(long);
					}
					this.SendPropertyChanged("School");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.Survey = this;
		}
		
		private void detach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.Survey = null;
		}
		
		private void attach_SurveyDates(SurveyDate entity)
		{
			this.SendPropertyChanging();
			entity.Survey = this;
		}
		
		private void detach_SurveyDates(SurveyDate entity)
		{
			this.SendPropertyChanging();
			entity.Survey = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClassLevels")]
	public partial class ClassLevel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private System.Nullable<int> _Weight;
		
		private EntitySet<Survey> _Surveys;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnWeightChanging(System.Nullable<int> value);
    partial void OnWeightChanged();
    #endregion
		
		public ClassLevel()
		{
			this._Surveys = new EntitySet<Survey>(new Action<Survey>(this.attach_Surveys), new Action<Survey>(this.detach_Surveys));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ClassLevelId", Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ClassLevelName", Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int")]
		public System.Nullable<int> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClassLevel_Survey", Storage="_Surveys", ThisKey="Id", OtherKey="ClassLevelId")]
		public EntitySet<Survey> Surveys
		{
			get
			{
				return this._Surveys;
			}
			set
			{
				this._Surveys.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Surveys(Survey entity)
		{
			this.SendPropertyChanging();
			entity.ClassLevel = this;
		}
		
		private void detach_Surveys(Survey entity)
		{
			this.SendPropertyChanging();
			entity.ClassLevel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Schools")]
	public partial class School : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _City;
		
		private System.Nullable<int> _StateId;
		
		private string _Zip;
		
		private EntitySet<Survey> _Surveys;
		
		private EntityRef<State> _State;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnAddress3Changing(string value);
    partial void OnAddress3Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateIdChanging(System.Nullable<int> value);
    partial void OnStateIdChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    #endregion
		
		public School()
		{
			this._Surveys = new EntitySet<Survey>(new Action<Survey>(this.attach_Surveys), new Action<Survey>(this.detach_Surveys));
			this._State = default(EntityRef<State>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SchoolId", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SchoolName", Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="VarChar(255)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(255)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="VarChar(255)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this.OnAddress3Changing(value);
					this.SendPropertyChanging();
					this._Address3 = value;
					this.SendPropertyChanged("Address3");
					this.OnAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(255)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateId", DbType="Int")]
		public System.Nullable<int> StateId
		{
			get
			{
				return this._StateId;
			}
			set
			{
				if ((this._StateId != value))
				{
					if (this._State.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStateIdChanging(value);
					this.SendPropertyChanging();
					this._StateId = value;
					this.SendPropertyChanged("StateId");
					this.OnStateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(25)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="School_Survey", Storage="_Surveys", ThisKey="Id", OtherKey="SchoolId")]
		public EntitySet<Survey> Surveys
		{
			get
			{
				return this._Surveys;
			}
			set
			{
				this._Surveys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="State_School", Storage="_State", ThisKey="StateId", OtherKey="Id", IsForeignKey=true)]
		public State State
		{
			get
			{
				return this._State.Entity;
			}
			set
			{
				State previousValue = this._State.Entity;
				if (((previousValue != value) 
							|| (this._State.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._State.Entity = null;
						previousValue.Schools.Remove(this);
					}
					this._State.Entity = value;
					if ((value != null))
					{
						value.Schools.Add(this);
						this._StateId = value.Id;
					}
					else
					{
						this._StateId = default(Nullable<int>);
					}
					this.SendPropertyChanged("State");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Surveys(Survey entity)
		{
			this.SendPropertyChanging();
			entity.School = this;
		}
		
		private void detach_Surveys(Survey entity)
		{
			this.SendPropertyChanging();
			entity.School = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seasons")]
	public partial class Season : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Weight;
		
		private EntitySet<SurveyDate> _SurveyDates;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnWeightChanging(string value);
    partial void OnWeightChanged();
    #endregion
		
		public Season()
		{
			this._SurveyDates = new EntitySet<SurveyDate>(new Action<SurveyDate>(this.attach_SurveyDates), new Action<SurveyDate>(this.detach_SurveyDates));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SeasonId", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SeasonName", Storage="_Name", DbType="VarChar(25)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="VarChar(25)")]
		public string Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Season_SurveyDate", Storage="_SurveyDates", ThisKey="Id", OtherKey="SeasonId")]
		public EntitySet<SurveyDate> SurveyDates
		{
			get
			{
				return this._SurveyDates;
			}
			set
			{
				this._SurveyDates.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SurveyDates(SurveyDate entity)
		{
			this.SendPropertyChanging();
			entity.Season = this;
		}
		
		private void detach_SurveyDates(SurveyDate entity)
		{
			this.SendPropertyChanging();
			entity.Season = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.States")]
	public partial class State : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private EntitySet<School> _Schools;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public State()
		{
			this._Schools = new EntitySet<School>(new Action<School>(this.attach_Schools), new Action<School>(this.detach_Schools));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="StateId", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="StateName", Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="State_School", Storage="_Schools", ThisKey="Id", OtherKey="StateId")]
		public EntitySet<School> Schools
		{
			get
			{
				return this._Schools;
			}
			set
			{
				this._Schools.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Schools(School entity)
		{
			this.SendPropertyChanging();
			entity.State = this;
		}
		
		private void detach_Schools(School entity)
		{
			this.SendPropertyChanging();
			entity.State = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Students")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private long _SurveyId;
		
		private EntitySet<StudentSurveyDate> _StudentSurveyDates;
		
		private EntityRef<Survey> _Survey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnSurveyIdChanging(long value);
    partial void OnSurveyIdChanged();
    #endregion
		
		public Student()
		{
			this._StudentSurveyDates = new EntitySet<StudentSurveyDate>(new Action<StudentSurveyDate>(this.attach_StudentSurveyDates), new Action<StudentSurveyDate>(this.detach_StudentSurveyDates));
			this._Survey = default(EntityRef<Survey>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="StudentId", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="BigInt NOT NULL")]
		public long SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					if (this._Survey.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSurveyIdChanging(value);
					this.SendPropertyChanging();
					this._SurveyId = value;
					this.SendPropertyChanged("SurveyId");
					this.OnSurveyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_StudentSurveyDate", Storage="_StudentSurveyDates", ThisKey="Id", OtherKey="StudentId")]
		public EntitySet<StudentSurveyDate> StudentSurveyDates
		{
			get
			{
				return this._StudentSurveyDates;
			}
			set
			{
				this._StudentSurveyDates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Survey_Student", Storage="_Survey", ThisKey="SurveyId", OtherKey="Id", IsForeignKey=true)]
		public Survey Survey
		{
			get
			{
				return this._Survey.Entity;
			}
			set
			{
				Survey previousValue = this._Survey.Entity;
				if (((previousValue != value) 
							|| (this._Survey.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Survey.Entity = null;
						previousValue.Students.Remove(this);
					}
					this._Survey.Entity = value;
					if ((value != null))
					{
						value.Students.Add(this);
						this._SurveyId = value.Id;
					}
					else
					{
						this._SurveyId = default(long);
					}
					this.SendPropertyChanged("Survey");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StudentSurveyDates(StudentSurveyDate entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_StudentSurveyDates(StudentSurveyDate entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentSurveyDates")]
	public partial class StudentSurveyDate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _StudentId;
		
		private long _SurveyDateId;
		
		private EntitySet<StudentSurveyRating> _StudentSurveyRatings;
		
		private EntityRef<Student> _Student;
		
		private EntityRef<SurveyDate> _SurveyDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnStudentIdChanging(long value);
    partial void OnStudentIdChanged();
    partial void OnSurveyDateIdChanging(long value);
    partial void OnSurveyDateIdChanged();
    #endregion
		
		public StudentSurveyDate()
		{
			this._StudentSurveyRatings = new EntitySet<StudentSurveyRating>(new Action<StudentSurveyRating>(this.attach_StudentSurveyRatings), new Action<StudentSurveyRating>(this.detach_StudentSurveyRatings));
			this._Student = default(EntityRef<Student>);
			this._SurveyDate = default(EntityRef<SurveyDate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="StudentSurveyDateId", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="BigInt NOT NULL")]
		public long StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentIdChanging(value);
					this.SendPropertyChanging();
					this._StudentId = value;
					this.SendPropertyChanged("StudentId");
					this.OnStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyDateId", DbType="BigInt NOT NULL")]
		public long SurveyDateId
		{
			get
			{
				return this._SurveyDateId;
			}
			set
			{
				if ((this._SurveyDateId != value))
				{
					if (this._SurveyDate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSurveyDateIdChanging(value);
					this.SendPropertyChanging();
					this._SurveyDateId = value;
					this.SendPropertyChanged("SurveyDateId");
					this.OnSurveyDateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentSurveyDate_StudentSurveyRating", Storage="_StudentSurveyRatings", ThisKey="Id", OtherKey="StudentSurveyDateId")]
		public EntitySet<StudentSurveyRating> StudentSurveyRatings
		{
			get
			{
				return this._StudentSurveyRatings;
			}
			set
			{
				this._StudentSurveyRatings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_StudentSurveyDate", Storage="_Student", ThisKey="StudentId", OtherKey="Id", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.StudentSurveyDates.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.StudentSurveyDates.Add(this);
						this._StudentId = value.Id;
					}
					else
					{
						this._StudentId = default(long);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SurveyDate_StudentSurveyDate", Storage="_SurveyDate", ThisKey="SurveyDateId", OtherKey="Id", IsForeignKey=true)]
		public SurveyDate SurveyDate
		{
			get
			{
				return this._SurveyDate.Entity;
			}
			set
			{
				SurveyDate previousValue = this._SurveyDate.Entity;
				if (((previousValue != value) 
							|| (this._SurveyDate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SurveyDate.Entity = null;
						previousValue.StudentSurveyDates.Remove(this);
					}
					this._SurveyDate.Entity = value;
					if ((value != null))
					{
						value.StudentSurveyDates.Add(this);
						this._SurveyDateId = value.Id;
					}
					else
					{
						this._SurveyDateId = default(long);
					}
					this.SendPropertyChanged("SurveyDate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StudentSurveyRatings(StudentSurveyRating entity)
		{
			this.SendPropertyChanging();
			entity.StudentSurveyDate = this;
		}
		
		private void detach_StudentSurveyRatings(StudentSurveyRating entity)
		{
			this.SendPropertyChanging();
			entity.StudentSurveyDate = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentSurveyRatings")]
	public partial class StudentSurveyRating : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _StudentSurveyDateId;
		
		private long _AnonStudentId;
		
		private int _WasBulliedValue;
		
		private System.Nullable<int> _IsBullyValue;
		
		private string _Comment;
		
		private EntityRef<AnonStudent> _AnonStudent;
		
		private EntityRef<StudentSurveyDate> _StudentSurveyDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnStudentSurveyDateIdChanging(long value);
    partial void OnStudentSurveyDateIdChanged();
    partial void OnAnonStudentIdChanging(long value);
    partial void OnAnonStudentIdChanged();
    partial void OnWasBulliedValueChanging(int value);
    partial void OnWasBulliedValueChanged();
    partial void OnIsBullyValueChanging(System.Nullable<int> value);
    partial void OnIsBullyValueChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public StudentSurveyRating()
		{
			this._AnonStudent = default(EntityRef<AnonStudent>);
			this._StudentSurveyDate = default(EntityRef<StudentSurveyDate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="StudentSurveyRatingId", Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentSurveyDateId", DbType="BigInt NOT NULL")]
		public long StudentSurveyDateId
		{
			get
			{
				return this._StudentSurveyDateId;
			}
			set
			{
				if ((this._StudentSurveyDateId != value))
				{
					if (this._StudentSurveyDate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentSurveyDateIdChanging(value);
					this.SendPropertyChanging();
					this._StudentSurveyDateId = value;
					this.SendPropertyChanged("StudentSurveyDateId");
					this.OnStudentSurveyDateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnonStudentId", DbType="BigInt NOT NULL")]
		public long AnonStudentId
		{
			get
			{
				return this._AnonStudentId;
			}
			set
			{
				if ((this._AnonStudentId != value))
				{
					if (this._AnonStudent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAnonStudentIdChanging(value);
					this.SendPropertyChanging();
					this._AnonStudentId = value;
					this.SendPropertyChanged("AnonStudentId");
					this.OnAnonStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WasBulliedValue", DbType="Int NOT NULL")]
		public int WasBulliedValue
		{
			get
			{
				return this._WasBulliedValue;
			}
			set
			{
				if ((this._WasBulliedValue != value))
				{
					this.OnWasBulliedValueChanging(value);
					this.SendPropertyChanging();
					this._WasBulliedValue = value;
					this.SendPropertyChanged("WasBulliedValue");
					this.OnWasBulliedValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBullyValue", DbType="Int")]
		public System.Nullable<int> IsBullyValue
		{
			get
			{
				return this._IsBullyValue;
			}
			set
			{
				if ((this._IsBullyValue != value))
				{
					this.OnIsBullyValueChanging(value);
					this.SendPropertyChanging();
					this._IsBullyValue = value;
					this.SendPropertyChanged("IsBullyValue");
					this.OnIsBullyValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(350)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnonStudent_StudentSurveyRating", Storage="_AnonStudent", ThisKey="AnonStudentId", OtherKey="Id", IsForeignKey=true)]
		public AnonStudent AnonStudent
		{
			get
			{
				return this._AnonStudent.Entity;
			}
			set
			{
				AnonStudent previousValue = this._AnonStudent.Entity;
				if (((previousValue != value) 
							|| (this._AnonStudent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AnonStudent.Entity = null;
						previousValue.StudentSurveyRatings.Remove(this);
					}
					this._AnonStudent.Entity = value;
					if ((value != null))
					{
						value.StudentSurveyRatings.Add(this);
						this._AnonStudentId = value.Id;
					}
					else
					{
						this._AnonStudentId = default(long);
					}
					this.SendPropertyChanged("AnonStudent");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentSurveyDate_StudentSurveyRating", Storage="_StudentSurveyDate", ThisKey="StudentSurveyDateId", OtherKey="Id", IsForeignKey=true)]
		public StudentSurveyDate StudentSurveyDate
		{
			get
			{
				return this._StudentSurveyDate.Entity;
			}
			set
			{
				StudentSurveyDate previousValue = this._StudentSurveyDate.Entity;
				if (((previousValue != value) 
							|| (this._StudentSurveyDate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StudentSurveyDate.Entity = null;
						previousValue.StudentSurveyRatings.Remove(this);
					}
					this._StudentSurveyDate.Entity = value;
					if ((value != null))
					{
						value.StudentSurveyRatings.Add(this);
						this._StudentSurveyDateId = value.Id;
					}
					else
					{
						this._StudentSurveyDateId = default(long);
					}
					this.SendPropertyChanged("StudentSurveyDate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SurveyClasses")]
	public partial class SurveyClass : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Teacher;
		
		private string _ClassName;
		
		private int _AnonStudentCount;
		
		private long _SurveyDateId;
		
		private EntitySet<AnonStudent> _AnonStudents;
		
		private EntityRef<SurveyDate> _SurveyDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnTeacherChanging(string value);
    partial void OnTeacherChanged();
    partial void OnClassNameChanging(string value);
    partial void OnClassNameChanged();
    partial void OnAnonStudentCountChanging(int value);
    partial void OnAnonStudentCountChanged();
    partial void OnSurveyDateIdChanging(long value);
    partial void OnSurveyDateIdChanged();
    #endregion
		
		public SurveyClass()
		{
			this._AnonStudents = new EntitySet<AnonStudent>(new Action<AnonStudent>(this.attach_AnonStudents), new Action<AnonStudent>(this.detach_AnonStudents));
			this._SurveyDate = default(EntityRef<SurveyDate>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SurveyClassId", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teacher", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Teacher
		{
			get
			{
				return this._Teacher;
			}
			set
			{
				if ((this._Teacher != value))
				{
					this.OnTeacherChanging(value);
					this.SendPropertyChanging();
					this._Teacher = value;
					this.SendPropertyChanged("Teacher");
					this.OnTeacherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this.OnClassNameChanging(value);
					this.SendPropertyChanging();
					this._ClassName = value;
					this.SendPropertyChanged("ClassName");
					this.OnClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnonStudentCount", DbType="Int NOT NULL")]
		public int AnonStudentCount
		{
			get
			{
				return this._AnonStudentCount;
			}
			set
			{
				if ((this._AnonStudentCount != value))
				{
					this.OnAnonStudentCountChanging(value);
					this.SendPropertyChanging();
					this._AnonStudentCount = value;
					this.SendPropertyChanged("AnonStudentCount");
					this.OnAnonStudentCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyDateId", DbType="BigInt NOT NULL")]
		public long SurveyDateId
		{
			get
			{
				return this._SurveyDateId;
			}
			set
			{
				if ((this._SurveyDateId != value))
				{
					if (this._SurveyDate.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSurveyDateIdChanging(value);
					this.SendPropertyChanging();
					this._SurveyDateId = value;
					this.SendPropertyChanged("SurveyDateId");
					this.OnSurveyDateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SurveyClass_AnonStudent", Storage="_AnonStudents", ThisKey="Id", OtherKey="SurveyClassId")]
		public EntitySet<AnonStudent> AnonStudents
		{
			get
			{
				return this._AnonStudents;
			}
			set
			{
				this._AnonStudents.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SurveyDate_SurveyClass", Storage="_SurveyDate", ThisKey="SurveyDateId", OtherKey="Id", IsForeignKey=true)]
		public SurveyDate SurveyDate
		{
			get
			{
				return this._SurveyDate.Entity;
			}
			set
			{
				SurveyDate previousValue = this._SurveyDate.Entity;
				if (((previousValue != value) 
							|| (this._SurveyDate.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SurveyDate.Entity = null;
						previousValue.SurveyClasses.Remove(this);
					}
					this._SurveyDate.Entity = value;
					if ((value != null))
					{
						value.SurveyClasses.Add(this);
						this._SurveyDateId = value.Id;
					}
					else
					{
						this._SurveyDateId = default(long);
					}
					this.SendPropertyChanged("SurveyDate");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AnonStudents(AnonStudent entity)
		{
			this.SendPropertyChanging();
			entity.SurveyClass = this;
		}
		
		private void detach_AnonStudents(AnonStudent entity)
		{
			this.SendPropertyChanging();
			entity.SurveyClass = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SurveyDates")]
	public partial class SurveyDate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.DateTime _DateTaken;
		
		private long _SurveyId;
		
		private System.Nullable<int> _SeasonId;
		
		private EntitySet<StudentSurveyDate> _StudentSurveyDates;
		
		private EntitySet<SurveyClass> _SurveyClasses;
		
		private EntityRef<Survey> _Survey;
		
		private EntityRef<Season> _Season;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnDateTakenChanging(System.DateTime value);
    partial void OnDateTakenChanged();
    partial void OnSurveyIdChanging(long value);
    partial void OnSurveyIdChanged();
    partial void OnSeasonIdChanging(System.Nullable<int> value);
    partial void OnSeasonIdChanged();
    #endregion
		
		public SurveyDate()
		{
			this._StudentSurveyDates = new EntitySet<StudentSurveyDate>(new Action<StudentSurveyDate>(this.attach_StudentSurveyDates), new Action<StudentSurveyDate>(this.detach_StudentSurveyDates));
			this._SurveyClasses = new EntitySet<SurveyClass>(new Action<SurveyClass>(this.attach_SurveyClasses), new Action<SurveyClass>(this.detach_SurveyClasses));
			this._Survey = default(EntityRef<Survey>);
			this._Season = default(EntityRef<Season>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SurveyDateId", Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SurveyDate", Storage="_DateTaken", DbType="DateTime NOT NULL")]
		public System.DateTime DateTaken
		{
			get
			{
				return this._DateTaken;
			}
			set
			{
				if ((this._DateTaken != value))
				{
					this.OnDateTakenChanging(value);
					this.SendPropertyChanging();
					this._DateTaken = value;
					this.SendPropertyChanged("DateTaken");
					this.OnDateTakenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveyId", DbType="BigInt NOT NULL")]
		public long SurveyId
		{
			get
			{
				return this._SurveyId;
			}
			set
			{
				if ((this._SurveyId != value))
				{
					if (this._Survey.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSurveyIdChanging(value);
					this.SendPropertyChanging();
					this._SurveyId = value;
					this.SendPropertyChanged("SurveyId");
					this.OnSurveyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasonId", DbType="Int")]
		public System.Nullable<int> SeasonId
		{
			get
			{
				return this._SeasonId;
			}
			set
			{
				if ((this._SeasonId != value))
				{
					if (this._Season.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSeasonIdChanging(value);
					this.SendPropertyChanging();
					this._SeasonId = value;
					this.SendPropertyChanged("SeasonId");
					this.OnSeasonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SurveyDate_StudentSurveyDate", Storage="_StudentSurveyDates", ThisKey="Id", OtherKey="SurveyDateId")]
		public EntitySet<StudentSurveyDate> StudentSurveyDates
		{
			get
			{
				return this._StudentSurveyDates;
			}
			set
			{
				this._StudentSurveyDates.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SurveyDate_SurveyClass", Storage="_SurveyClasses", ThisKey="Id", OtherKey="SurveyDateId")]
		public EntitySet<SurveyClass> SurveyClasses
		{
			get
			{
				return this._SurveyClasses;
			}
			set
			{
				this._SurveyClasses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Survey_SurveyDate", Storage="_Survey", ThisKey="SurveyId", OtherKey="Id", IsForeignKey=true)]
		public Survey Survey
		{
			get
			{
				return this._Survey.Entity;
			}
			set
			{
				Survey previousValue = this._Survey.Entity;
				if (((previousValue != value) 
							|| (this._Survey.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Survey.Entity = null;
						previousValue.SurveyDates.Remove(this);
					}
					this._Survey.Entity = value;
					if ((value != null))
					{
						value.SurveyDates.Add(this);
						this._SurveyId = value.Id;
					}
					else
					{
						this._SurveyId = default(long);
					}
					this.SendPropertyChanged("Survey");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Season_SurveyDate", Storage="_Season", ThisKey="SeasonId", OtherKey="Id", IsForeignKey=true)]
		public Season Season
		{
			get
			{
				return this._Season.Entity;
			}
			set
			{
				Season previousValue = this._Season.Entity;
				if (((previousValue != value) 
							|| (this._Season.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Season.Entity = null;
						previousValue.SurveyDates.Remove(this);
					}
					this._Season.Entity = value;
					if ((value != null))
					{
						value.SurveyDates.Add(this);
						this._SeasonId = value.Id;
					}
					else
					{
						this._SeasonId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Season");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StudentSurveyDates(StudentSurveyDate entity)
		{
			this.SendPropertyChanging();
			entity.SurveyDate = this;
		}
		
		private void detach_StudentSurveyDates(StudentSurveyDate entity)
		{
			this.SendPropertyChanging();
			entity.SurveyDate = null;
		}
		
		private void attach_SurveyClasses(SurveyClass entity)
		{
			this.SendPropertyChanging();
			entity.SurveyDate = this;
		}
		
		private void detach_SurveyClasses(SurveyClass entity)
		{
			this.SendPropertyChanging();
			entity.SurveyDate = null;
		}
	}
}
#pragma warning restore 1591
